### ISSUE TITLE
Issue with "Angular CLI", "Webpack 5", "Webpack Module Federation" and "LicenseWebpackPlugin"

### ISSUE THREAD

**Issue by abadakhshan** [xz64/license-webpack-plugin#95]
It seems there is an issue when you are using this combination 

"Angular CLI", "Webpack 5", "Webpack Module Federation" and "LicenseWebpackPlugin"

Error log:
```

[error] HookWebpackError: ENOENT: no such file or directory, open '\package.json'
    at makeWebpackError (D:\MyGit\narik-pluggable-dashboard-sample\node_modules\webpack\lib\HookWebpackError.js:49:9)
    at D:\MyGit\narik-pluggable-dashboard-sample\node_modules\webpack\lib\Compilation.js:2383:12
    at eval (eval at create (D:\MyGit\narik-pluggable-dashboard-sample\node_modules\tapable\lib\HookCodeFactory.js:33:10), <anonymous>:29:1)
    at fn (D:\MyGit\narik-pluggable-dashboard-sample\node_modules\webpack\lib\Compilation.js:373:17)
    at _next4 (eval at create (D:\MyGit\narik-pluggable-dashboard-sample\node_modules\tapable\lib\HookCodeFactory.js:33:10), <anonymous>:26:1)
    at eval (eval at create (D:\MyGit\narik-pluggable-dashboard-sample\node_modules\tapable\lib\HookCodeFactory.js:33:10), <anonymous>:45:1)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
-- inner error --
Error: ENOENT: no such file or directory, open '\package.json'
    at Object.openSync (fs.js:458:3)
    at Object.readFileSync (fs.js:360:35)
    at CacheBackend.provideSync (D:\MyGit\narik-pluggable-dashboard-sample\node_modules\webpack\node_modules\enhanced-resolve\lib\CachedInputFileSystem.js:233:32)
    at WebpackFileSystem.readFileAsUtf8 (D:\MyGit\narik-pluggable-dashboard-sample\node_modules\license-webpack-plugin\dist\WebpackFileSystem.js:52:24)
    at PluginChunkReadHandler.getPackageJson (D:\MyGit\narik-pluggable-dashboard-sample\node_modules\license-webpack-plugin\dist\PluginChunkReadHandler.js:35:43)
    at PluginChunkReadHandler.processModule (D:\MyGit\narik-pluggable-dashboard-sample\node_modules\license-webpack-plugin\dist\PluginChunkReadHandler.js:45:40)
    at D:\MyGit\narik-pluggable-dashboard-sample\node_modules\license-webpack-plugin\dist\PluginChunkReadHandler.js:29:23
    at WebpackModuleFileIterator.internalCallback (D:\MyGit\narik-pluggable-dashboard-sample\node_modules\license-webpack-plugin\dist\WebpackModuleFileIterator.js:28:13)
    at WebpackModuleFileIterator.iterateFiles (D:\MyGit\narik-pluggable-dashboard-sample\node_modules\license-webpack-plugin\dist\WebpackModuleFileIterator.js:8:9)
    at D:\MyGit\narik-pluggable-dashboard-sample\node_modules\license-webpack-plugin\dist\PluginChunkReadHandler.js:27:32
```

It happens for modules which **directory property** have not been specified on them.
(I think modules that are created with Module Federation)

You can see sample repo [here](https://github.com/NarikMe/narik-pluggable-dashboard-sample/tree/upgrade-to-angular-next)

**Comment by xz64** [comment]
@abadakhshan Do you have a simpler test case? The build takes quite long on the repo which you linked, and I am not sure which command to run to reproduce the issue. I tried the commands in the README but didn't run into the error.

**Comment by jquense** [comment]
I think you may be able to reproduce this with this webpack config:

it assumes two files `index1.js` and `index2.js`
```
module.exports = [
  {
    name: 'initial',
    entry: './index1.js',
    output: {
      path: `${__dirname}/build`,
      filename: 'initial_out.js',
    },
  },
  {
    name: 'second',
    dependencies: ['initial'],
    entry: ['./build/initial_out.js', './index2.js'],
    output: {
      path: `${__dirname}/build`,
    },
  },
];

```

**Comment by xz64** [comment]
@jquense This webpack config doesn't include LicenseWebpackPlugin. Do you have a more complete example?

**Comment by jquense** [comment]
oops sorry, added it. I can put something more complete together at some point, but i'm a bit short on time right now. The core issue is that you can include "modules" that are local to the root (same would likely apply for federation and maybe DDLs). Here the `initial` chunk is treated like it's a third party dep and the plugin tries to find a package.json for it at `/package.json`

**Comment by xz64** [comment]
I tried with the suggested webpack config and didn't run into any error. Please add a full reproducible test case when you have some time. Thanks

**Comment by abadakhshan** [comment]
Hello @xz64 

you can run ng build todo --prod to see the error

**Comment by xz64** [comment]
@abadakhshan Thanks, I was able to reproduce the issue from your repo. I will investigate it further.

**Comment by xz64** [comment]
Fixed in v2.3.12

**Comment by abadakhshan** [comment]
Thank you  @xz64 
But the issue still exists in my repo.


[getActualFilename](https://github.com/xz64/license-webpack-plugin/blob/f4af707794962905e11eb26787f99df56c54d90a/src/WebpackModuleFileIterator.ts#L33)  returns

`"container entry (default) [["./Viewer",{"import":["./plugins/todo/src/app/viewer/viewer.component.ts"]}],["./Designer",{"import":["./plugins/todo/src/app/designer/designer.component.ts"]}]]"`

for this input

`"container entry (default) [["./Viewer",{"import":["./plugins/todo/src/app/viewer/viewer.component.ts"]}],["./Designer",{"import":["./plugins/todo/src/app/designer/designer.component.ts"]}]]"`

and the callback is called with 

```
{
  directory: ""
  name: "narik-dashboard"
}
```

**Comment by xz64** [comment]
I will look into this

**Comment by xz64** [comment]
@abadakhshan  Please try v2.3.13. I was not able to reproduce the issue from your repo, but I have added one check to ignore container entry modules.

**Comment by abadakhshan** [comment]
Thank you @xz64

The issue was solved with v2.3.13.

**Comment by jquense** [comment]
@xz64 i'm still hitting this on 2.3.13 not sure why, trying to debug but having a hard time simplifying the case from our app

**Comment by xz64** [comment]
@jquense  You can try console.log(filename) in node_modules/license-webpack-plugin/dist/WebpackModuleFileIterator.js in the first line of `WebpackModuleFileIterator.prototype.getActualFilename` . It should log the filename causing the issue before failing.

**Comment by jquense** [comment]
yeah  while debugging through it, the module is: `'ignored|ws'` which i'm not sure what the source is...

**Comment by xz64** [comment]
Are you using [IgnorePlugin](https://webpack.js.org/plugins/ignore-plugin/) by any chance?

**Comment by jquense** [comment]
As far as i can tell we aren't, but it's possible it's happening indirectly through another plugin.

**Comment by jquense** [comment]
seems like this identifier format may be relatively dynamic? https://github.com/webpack/webpack/blob/master/lib/NormalModule.js#L273 Might be worth generically splitting on '|' in getActualFilename perhaps?

**Comment by xz64** [comment]
@jquense  Can you try adding condition `filename.indexOf('ignored|') === 0 ||` to the first if statement in WebpackModuleFileIterator.prototype.getActualFilename and see if you get any other errors? Thanks

I think `inogred|ws` may be related to some websocket library. Are you using LicenseWebpackPlugin in development builds (e.g. webpack-dev-server) or only in production builds?

**Comment by xz64** [comment]
@jquense  I have pushed a fix for the `ignored|ws` error in 2.3.14.
